ko_fi: heliomarpm
liberapay: heliomarpm
custom: [
  "https://www.paypal.com/donate?business=KBVHLR7Z9V7B2&no_recurring=0&currency_code=USD",
  "https://www.paypal.com/donate?business=KBVHLR7Z9V7B2&no_recurring=0&currency_code=BRL"
 ]
