name: "⭐ New Feature / Enhancement Request"
description: Propose something new.
labels:
- enhancement
- needs-triage

body:
- type: markdown
  attributes:
    value: |
      Please limit one request per issue.

- type: textarea
  attributes:
    label: Description of the new feature / enhancement
    placeholder: |
      A clear and concise description of what is the expected behavior of the proposed feature?
  validations:
    required: true

- type: textarea
  attributes:
    label: Scenario when this would be used?
    placeholder: |
      What is the scenario this would be used?  Why is this important?
  validations:
    required: true
