name: Electron CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   runs-on: ${{ matrix.os }}
    
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]

  #   steps:
  #     - uses: actions/checkout@v2

      # - name: Install Node.js, NPM and Yarn
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 13.x

      # - name: Build/release Electron app
      #   uses: heliomarpm/action-electron-builder@v1
      #   with:
      #     # GitHub token, automatically provided to the action
      #     # (No need to define this secret in the repo settings)
      #     github_token: ${{ secrets.github_token }}

      #     # If the commit is tagged with a version (e.g. "v1.0.0"),
      #     # release the app after building
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}

  build_on_linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
            
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install All Dependencies 
        run: npm install

      - name: Build release
        run: npm run build-linux